---
title: "Case study"
output:
  html_document:
    highlight: pygments
  pdf_document: default
---
# Overview
```{r}
# Load data observations
suppressWarnings(library(readxl))
t24obs <- read_excel('../data/t24.xlsx')

# TODO: Remove after fixing source data
for (idx in 1:nrow(t24obs)) {
  
  if (t24obs[idx,'property']=='wt_numattr') {
    numattr <- as.integer(t24obs[idx,'value'])
  }

  if (t24obs[idx,'property']=='wt_fillrec') {
    fillrec <- as.integer(t24obs[idx,'value'])
    if (fillrec==0) {
      t24obs[idx,'value'] <- NA
    } else {
      if (numattr > 0) {
        t24obs[idx,'value'] <- as.integer(t24obs[idx,'value'])/numattr
      }
    }
  }
}

# Observations data frame structure
str(t24obs, strict.width='cut', width=70)

#Summary of object properties observed
table(t24obs$property)

#Sample observations of each property
set.seed(123)
sobs <- t(sapply(unique(t24obs$property), function(x) {
  sobs <- t24obs[t24obs$property==x,]; sobs[sample(1:nrow(sobs), 1), ] }))
print(as.data.frame(sobs), row.names=FALSE)

# Convert to wide format
source('func.R')
t24 <- analysis('vizgraph', 't24obs')
obsw <- browseData(t24)
str(obsw, give.attr=FALSE, strict.width='cut', width=70)
```

# Plotting 
```{r}
# Plot parameters
par(mar=c(4,4,3,1), oma=c(1,1,2,0), cex.lab=1)
layout(matrix(c(1,2,4,1,3,5), nrow=3))

# Modularization plot
obsw[grepl('ERR_', obsw$mbrp_module), 'mbrp_module'] <- '?'
 
md <- obsw[!is.na(obsw$mbrp_module), c('object','mbrp_module','mbrp_localcore','wt_numrec')]
mcore <- data.frame(table(md[md$mbrp_localcore=='core','mbrp_module']))
mlocal <- data.frame(table(md[md$mbrp_localcore=='local','mbrp_module']))
maggr <- aggregate(wt_numrec~mbrp_module, md, sum)

maggr$width = round(log10(1+maggr$wt_numrec))
m <- merge(mcore, mlocal, by="Var1", all.x=TRUE)
m <- merge(m, maggr, by.x="Var1", by.y="mbrp_module")
m <- t(m)
m[is.na(m)] <- 0

# TODO: Record count not taking into account history very wrong?
mods <- rbind(as.numeric(m[2, ]), as.numeric(m[3, ]))

pmain <- 'Modularization'
pxlab <- 'module codes (?: unknown; bar width: number of records [log10(1+sum(wt_numrec))]'
pylab <- 'number of tables'
pleg <- c('core','local')
barplot(mods, names=m[1, ], width=as.numeric(m[5, ]), space=0, main=pmain, cex.names=0.8, xlab=pxlab, ylab=pylab, legend=pleg)

# Plot number of records and attributes
with(obsw, {
  pmain <- 'Number of Records'
  pxlab <- 'records per table [log10(1+wt_numrec)]'
  pylab <- 'frequency'
  hist(log10(1+wt_numrec), breaks=20, main=pmain, xlab=pxlab, ylab=pylab)
  text(4, 1000, paste('Total number of tables:', sum(mods)))
  text(4, 800, paste('Total number of records:', sum(wt_numrec, na.rm=TRUE)))
  
  pmain <- 'Number of Attributes'
  pxlab <- 'attributes per record [wt_numattr]'
  hist(wt_numattr, breaks=20, main=pmain, xlab=pxlab, ylab=pylab)
  text(120, 450, paste('Mean number of attributes:', round(mean(wt_numattr, na.rm=TRUE))))
})

# Sizing plot
cb <- c(0, 20, 50, 100, 500, seq(1000, 7000, by=1000))
volrec <- obsw[!is.na(obsw$wt_volrec), c('wt_volrec','wt_numrec')]
vr <- cut(volrec$wt_volrec, breaks=cb, include.lowest=TRUE)
vr <- table(vr)/length(vr)*100

wt_volattr <- obsw[!is.na(obsw$wt_volattr), 'wt_volattr']
va <- cut(wt_volattr, breaks=cb, include.lowest=TRUE)
va <- table(va)/length(va)*100

pxlab <- 'item size (bytes) [wt_volrec; wt_volattr]'
pylab <- 'percent of items'
pleg <- c('records','attributes')
barplot(rbind(vr, va), beside=TRUE, main='Sizes', xlab=pxlab, ylab=pylab, legend=pleg)
totsize <- round(sum(volrec$wt_volrec*volrec$wt_numrec)/1024/1024)
text(20, 50, paste('Total data size:', totsize, 'MB'))

# Prepare data for fill plot
wt_fillrec <- obsw[!is.na(obsw$wt_fillrec), 'wt_fillrec']*100
fr <- cut(wt_fillrec, breaks=seq(0, 100, by=10), include.lowest=TRUE)
fr <- table(fr)/length(fr)*100

wt_fillattr <- obsw[!is.na(obsw$wt_fillattr), 'wt_fillattr']*100
fa <- cut(wt_fillattr, breaks=seq(0, 100, by=10), include.lowest=TRUE)
fa <- table(fa)/length(fa)*100

pxlab <- 'completeness percentage [wt_fillrec; wt_fillattr]'
barplot(rbind(fr, fa), beside=TRUE, main='Completeness', xlab=pxlab, ylab=pylab, legend=pleg)

# TODO: Shouldn't total record and attribute completenes match?
# text(18, 50, paste('Mean record completeness (%):', round(mean(wt_fillrec, na.rm=TRUE))))
text(18, 30, paste0('Mean completeness: ', round(mean(wt_fillattr, na.rm=TRUE)), '%'))

mtext("Summary of Live Data Observations", outer=TRUE, cex=1.3)
```

